services:
  # Develop
  develop:
    image: py_database_wrapper
    container_name: py_database_wrapper_develop
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: development
      args:
        - GIT_NAME
        - GIT_EMAIL
    secrets:
      - user_ssh_key
    volumes:
      - ./:/srv/app

secrets:
  user_ssh_key:
    file: $LOCAL_SSH_KEY_PATH
